// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "zQVQPOOO_QPO'#CeOOQO'#Cb'#CbQVQPOOOOQO'#Ce'#CeOOQO,59P,59POOQO-E6`-E6`",
  stateData: "g~OPOS~ORSOSPO~ORTOTTO~O",
  goto: "eYPPPPPPZPPaQRORURTQOR",
  nodeNames: "⚠ Comment all Newline Phrase Eof",
  maxTerm: 9,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "#[~RZOXtYZ!cZ]t]^!h^stst!nt;'St;'S;=`!]<%l~t~Ot~~#V~yUS~OXtZ]t^stt;'St;'S;=`!]<%lOt~!`P;=`<%lt~!hOR~~!kPYZ!c~!sSP~OY!nZ;'S!n;'S;=`#P<%lO!n~#SP;=`<%l!n~#[OT~",
  tokenizers: [0],
  topRules: {"all":[0,2]},
  tokenPrec: 0
})
