name: Build LibASCA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: girv98/asca-rust
      - name: Install WasmPack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack build --release --target web --out-dir libasca
      - uses: actions/upload-artifact@v4
        with:
          name: libasca-out
          path: ./libasca/*

  merge:
    runs-on: ubuntu-latest
    needs: [build_lib]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: libasca-out
      - run: ls -al
