name: Vercel Deployment

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_lib:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest libasca release
        id: latestrelease
        run: |
          echo "VERSION=$(curl -s https://api.github.com/repos/girv98/asca-rust/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT
      
      - name: Confirm latest libasca release
        run: |
          echo ${{ steps.latestrelease.outputs.VERSION }}
      
      - name: Checkout latest libasca release
        uses: actions/checkout@v4
        with:
          repository: girv98/asca-rust
          ref: ${{ steps.latestrelease.outputs.VERSION }}
      
      - name: Install WasmPack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build libasca 
        run: wasm-pack build --enable-bulk-memory --release --target web --out-dir libasca

      - uses: actions/upload-artifact@v4
        with:
          name: libasca-out
          path: ./libasca

  deploy_vercel:
    runs-on: ubuntu-latest
    needs: [build_lib]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download libasca
        uses: actions/download-artifact@v4
        with:
          name: libasca-out
          path: ./libasca/

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Env Info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}